### ISSUE TITLE
GoogleAnalyticsBlocker should block ssl.google-analytics.com too

### ISSUE THREAD

**Issue by cjwatson** [davidpob99/webextensions#1]
For HTTPS sites, my understanding is that Google Analytics recommends (or at least has recommended in the past) using `ssl.google-analytics.com` rather than `www.google-analytics.com`.  Could you block that too?

It might be worth simply blocking everything under `google-analytics.com`.

**Comment by davidpob99** [comment]
@cjwatson It has been updated in version 1.0.1, thank you
