### ISSUE TITLE
Add Some Icon

### ISSUE THREAD

**Issue by antuketot76** [davidpob99/webextensions#2]
Would like to suggest for you to added some icon inside URL address field.

![ad17813c24d220494f4ee0693233aec9](https://user-images.githubusercontent.com/33280865/34329438-a5278544-e932-11e7-924a-670d2663cab7.jpg)

Easy for user to view and have a option to block the google analytic.
That snapshot sample was taken from extension inside Opera browser.
Here's the link [https://www.igorware.com/extensions/block-yourself-from-analytics](url)

**Comment by davidpob99** [comment]
I have added an icon in the version 1.1.0. If you click the button, it will disable the blocker and if you press it again, it will enable the blocker and so on.

The update it is ready in the Mozilla Add-ons.

Thanks.
